## Shared type definitions for Block Defense
class_name Types
extends RefCounted

enum GamePhase { BUILD, COMBAT }
enum MaterialTier { WOOD = 1, SCRAP_WOOD = 2, SOLID_METAL = 3, COPPER = 4, IRON_PLATES = 5, STEEL = 6, DIAMOND = 7, OBSIDIAN = 8 }
enum WeaponType { SLINGSHOT, SPEAR, BOW, CATAPULT, BALLISTA, TREBUCHET, CANNON, EXPLODING_SHELLS, ARTILLERY, MACHINE_GUN, GRENADE_LAUNCHER, BAZOOKA, MISSILE, RAILGUN, LASER, NUCLEAR_BOMB }
enum EnemyType { ZOMBIE, SKELETON, SLIME, TANK_BOSS }
enum TileType { GRASS, PATH, CASTLE, BLOCKED, OCCUPIED }
